### ISSUE TITLE
自己数据集训练

### ISSUE THREAD

**Issue by wwzstudy** [LS4GAN/uvcgan2#37]
An error occurred while running trainslation.py
![Uploading 1721626799107.png…]()

**Comment by wwzstudy** [comment]
Epoch 1 / 500:   0%|                                                                                  | 0/201 [00:00<?, ?it/s]<class 'tuple'>
<class 'list'>
Traceback (most recent call last):
  File "trainslation.py", line 145, in <module>
    train(args_dict)
  File "/hy-tmp/uvcgan2/train/train.py", line 73, in train
    metrics = training_epoch(
  File "/hy-tmp/uvcgan2/train/train.py", line 25, in training_epoch
    model.set_input(batch)
  File "/hy-tmp/uvcgan2/cgan/model_base.py", line 45, in set_input
    self._set_input(inputs, domain)
  File "/hy-tmp/uvcgan2/cgan/uvcgan2.py", line 190, in _set_input
    set_two_domain_input(self.images, inputs, domain, self.device)
  File "/hy-tmp/uvcgan2/cgan/funcs.py", line 6, in set_two_domain_input
    images.real_a = inputs[0].to(device, non_blocking = True)
AttributeError: 'list' object has no attribute 'to'

**Comment by usert5432** [comment]
Hi @wwzstudy,

Thank you for reporting this problem. The error you've encountered is rather unusual. To help us diagnose the issue more effectively, could you please confirm whether you're using a custom dataset for the training?

I suspect there may be some issue with a dataset returning a list of values (like [ image, labels ]), instead of just images.
